### ISSUE TITLE
How to stop the bgAutoEvict goroutine?

### ISSUE THREAD

**Issue by rgl** [jamiealquiza/bicache#84]
When AutoEvict is turned on, how do we stop the bgAutoEvict goroutine after we are done with the cache?

**Comment by jamiealquiza** [comment]
Hey @rgl - I meant to add something like a close method for use cases where bicache may be only used for a period of the parent program's lifetime. I'll get this in shortly.

**Comment by jamiealquiza** [comment]
merged and available in the v2.0.0 release
